### ISSUE TITLE
Zrobić komponent Technology bar

### ISSUE THREAD

**Issue by aexol** [jamstackpb/main#14]

**Comment by aexol** [comment]
![image](https://user-images.githubusercontent.com/779748/130095087-c8763bac-9560-4bdc-9d3a-1c051f2f607c.png)

**Comment by aexol** [comment]
![image](https://user-images.githubusercontent.com/779748/130095243-478bbb81-5b10-45ae-8aa8-eeeabb83dadc.png)

**Comment by aexol** [comment]
Stworzyć komponent, który przyjmuje Array obiektów i je wyświetla w karuzeli
https://github.com/aexol-studio/rerousel

```ts
interface LogoCloudProps{
  images:Array<{imageUrl:string; link:string}>
}
```

Technologie:
- TypeScript
- NextJS
- React
- Github
- Discord
- GraphQL
- Javascript
- HTML
- CSS

**Comment by shuturanusplsbai** [comment]
Miałem tonę problemów przez które nie mogłem tego Tech bara pull'ować normalnie, więc wstawiam to w takiej formie.

**To jest kod do "Rerousel.tsx", do ścieżki "@/src/components/molecules".**

`import styled from '@emotion/styled';
import React, { useRef } from 'react';
import { Rerousel } from 'rerousel';

const Main = styled.div`
    background: #e6e8fa;
    color: #fdf;
    padding: 10px;
    padding-bottom: 30px;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
`;

const Item = styled.div`
    display: flex;
    justify-content: center;
    align-items: center;

    width: 20%;
    min-width: 100px;
    background-color: #e6e8fa;
`;

const Images: { imageUrl: string; link: string; key: string }[] = [
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
        link: 'https://www.typescriptlang.org/',
        key: '1',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Nextjs-logo.svg',
        link: 'https://nextjs.org/',
        key: '2',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
        link: 'https://reactjs.org/',
        key: '3',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Ei-sc-github.svg',
        link: 'https://github.com/',
        key: '4',
    },
    {
        imageUrl: 'https://external-content.duckduckgo.com/ip3/discord.com.ico',
        link: 'https://discord.com/',
        key: '5',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/17/GraphQL_Logo.svg',
        link: 'https://graphql.org/',
        key: '6',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg',
        link: 'https://www.javascript.com/',
        key: '7',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg',
        link: 'https://en.wikipedia.org/wiki/HTML',
        key: '8',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg',
        link: 'https://en.wikipedia.org/wiki/CSS',
        key: '9',
    },
];

interface LogoCloudProps {
    images: Array<{ imageUrl: string; link: string; key: string }>;
}

export const Techbar: React.FC<LogoCloudProps> = ({ images }) => {
    const customerLogo = useRef(null);

    return (
        <Main>
            <Rerousel itemRef={customerLogo} interval={3000} stop={false}>
                {Images.map(({ imageUrl, link, key }) => {
                    return (
                        <Item ref={customerLogo} key={key}>
                            <a href={link}>
                                <img
                                    style={{
                                        padding: '10px',
                                        background: 'white',
                                        height: '180px',
                                        width: '180px',
                                        display: 'flex',
                                        justifyContent: 'center',
                                    }}
                                    src={imageUrl}
                                />
                            </a>
                        </Item>
                    );
                })}
            </Rerousel>
        </Main>
    );
};
`

**_OSTRZEŻENIE: Trzeba zainstalować "Rerousel"_**

**To jest kod do dodania do pliku index.tsx w lokacji "@/src/components/molecules"**

`export * from './Rerousel';`

**To jest kod do dodania do pliku index.tsx w lokacji "@/src/pages"**

```
import { Techbar } from '@/src/components';
//... poniższa linijka Ma być bezpośrednio poniżej "<Cards />"
<Techbar images={[]} />
```
