### ISSUE TITLE
Podstrona indywidualnego blogposta

### ISSUE THREAD

**Issue by aexol** [jamstackpb/main#35]
![image](https://user-images.githubusercontent.com/779748/133639905-6ba94631-62ce-4b34-a3a9-5c65055ef401.png)

**Comment by SMATEO49** [comment]
@aexol jakiej czcionki użyć?
Ponieważ ta, której używamy ma inne kreski w porównaniu z tą na zdjęciu (kreski w ń, ś, ź) i trochę inne proporcje kropek do całych liter
